### ISSUE TITLE
Device not responding

### ISSUE THREAD

**Issue by somacoder** [mbientlab/MetaWear-SDK-Python#2]
Despite being able to connect and list services and characteristics in both gatttool and pygatt, whenever I go to connect the device using this library, I always get a response the the device is not responding after it tries for about a minute.

>>> status = device.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mbientlab/metawear/__init__.py", line 152, in connect
    for s in self.gatt.discover_primary():
RuntimeError: Device is not responding!

**Comment by scaryghost** [comment]
What BlueZ version and Linux distro are you using?

**Comment by somacoder** [comment]
I am on Rasbian Jessie Lite. The command `bluetoothd -v` reveals version 5.23. However, the command `bluetoothctl -v` reveals version 5.46.

**Comment by somacoder** [comment]
I should also mention that I have enabled BLE as well by using the command `sudo ~/bluez-*/tools/btmgmt -i hci0 le on`

**Comment by scaryghost** [comment]
I cannot reliably reproduce this issue on the RPi3 we have in the office.  The example scripts will timeout on occasion at either the connect or service discovery, but then will work 5-6 times in a row no problem.

Our Pi is running kernel 4.9.35 also with bluez 5.23.  I start the adapter with `hciconfig hci0 up` but it's highly unlikely this is the root cause of the problem.
