### ISSUE TITLE
No matching distribution found for gattlib==0.20171002 (from metawear)

### ISSUE THREAD

**Issue by onshoremanover** [mbientlab/MetaWear-SDK-Python#6]
Noob here. I run on raspbian-stretch-lite... on a raspberrypi zero w

I have installed all the dependencies for gattlib and as you can see, gattlib version 0.20171002 was successfully installed.

These are the commands I typed in the terminal.

$ pip install git+https://github.com/mbientlab/pygattlib.git@master#egg=gattlib
$ pip install metawear

- Successfully installed gattlib-0.20171002
- pi@raspberrypi:~ $ pip install metawear
- Collecting metawear
- Collecting gattlib==0.20171002 (from metawear)
 -  Could not find a version that satisfies the requirement gattlib==0.20171002 (from metawear) (from versions: 0.20150119.linux-x86_64, 0.20150119, 0.20150130, 0.20150131, 0.20150805)
No matching distribution found for gattlib==0.20171002 (from metawear)

**Comment by hbldh** [comment]
Doing investigations on this issue in hbldh/pymetawear#47.

**Comment by scaryghost** [comment]
Hrm, dependency links was working back then when the SDK was uploaded to PyPi.  Maybe the project should be using a requirements file instead.

**Comment by hbldh** [comment]
The `—process_dependency_links` works well for me, albeit with DeprecationWarnings. I tend to avoid using it due to that.
This specific question seems to be happening on RPi Zero only.

It might be a reasonable idea to vendor the pygattlib in the metawear package to avoid the version confusion. If it is distributed not as a dependency but as a bundled software then no dependency link is needed. It is Alv2 licensed, so it should work fine, no?

**Comment by scaryghost** [comment]
Yeah, it should be OK to combine them into one package, however, we are planning on swapping out the back end ble library with [libblepp](https://github.com/edrosten/libblepp) so I'd prefer not dealing with pygattlib more than necessary.

**Comment by scaryghost** [comment]
The latest release ([v0.4.0](https://github.com/mbientlab/MetaWear-SDK-Python/releases/tag/0.4.0)) has replaced gattlib with another ble library so this issue is no longer relevant.
